### ISSUE TITLE
The relative positioning has not been realized. There is ambiguity with the document.

### ISSUE THREAD

**Issue by JenmingTang** [vuejs/router#2046] opened 2023-11-20 12:39 UTC
### Vue version

3

### Link to minimal reproduction

https://stackblitz.com/edit/vitejs-vite-1a2evq?file=src%2Frouter%2Findex.js

### Steps to reproduce

>vue-router@4 Relative redirection

```javascript
//src\components\Profile.vue exited
const routes = [
  {
    path: '/users/:id/posts',
    redirect: to => {
      return 'profile'
    }
  },
  {
    path: '/users/:id/profile',
    component: () => import('@/components/Profile.vue')
  }
]
```

### What is expected?

# [Below StackBlitz](https://vite.new/vue)

```javascript
https://vitejsvite1a2evq-4nhl--5173--6a615fc0.local-corp.webcontainer.io/users/123/posts
-->
https://vitejsvite1a2evq-4nhl--5173--6a615fc0.local-corp.webcontainer.io/users/123/profile

//The page has the parameter value of the past.
```

# Below my project
>According to the official website document, you should jump like this.

```javascript
http://localhost:5173/users/123/posts
-->
http://localhost:5173/users/123/profile
```

### What is actually happening?

# [Below StackBlitz](https://vite.new/vue)

```javascript
https://vitejsvite1a2evq-4nhl--5173--6a615fc0.local-corp.webcontainer.io/users/123/posts
-->
https://vitejsvite1a2evq-4nhl--5173--6a615fc0.local-corp.webcontainer.io/users/123/posts

//The page is blank. Nor did it not jump correctly.
```

>But the fact is that it jumps like this.
Prerequisition, I try to visit http://localhost:5173/users/123/profile too. It's well. 

```javascript
http://localhost:5173/users/123/posts
-->
http://localhost:5173/profile
```

### System Info

```shell
System:
    OS: Windows 10 10.0.18363
    CPU: (8) x64 Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
    Memory: 2.08 GB / 15.84 GB
  Binaries:
    Node: 18.18.0 - C:\Program Files\nodejs\node.EXE
    npm: 9.8.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: Spartan (44.18362.449.0)
```

**Comment by posva** [comment] 2023-11-20 22:44
Duplicate of https://github.com/vuejs/router/issues/1902

**Closed by posva** 2023-11-20 22:44 UTC
