### ISSUE TITLE
How to deal with the Property missing of ComponentPublicInstance?

### ISSUE THREAD

**Issue by ssshooter** [vuejs/router#1421] opened 2022-05-27 08:49 UTC
### Version
4.0.15

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/kind-poincare-w7jv2u?file=/src/views/Home.vue)

### Steps to reproduce
```vue
data() {
    return {
      isMounted: true,
    }
  },
beforeRouteEnter(to, from, next) {
    next((vm) => {
      if (to.meta.from.includes(from.path) || vm.isMounted) {
        vm.isMounted= false
        vm.fetch()
      }
    })
  }
```

### What is expected?
Be able to access `isMounted` of `vm`

### What is actually happening?
`Property 'mount' does not exist on type 'ComponentPublicInstance<{}, {}, {}, {}, {}, {}, {}, {}, false, ComponentOptionsBase<any, any, any, any, any, any, any, any, any, {}>>'.`

![image](https://user-images.githubusercontent.com/13051472/170665483-7fb96e41-5e2a-4175-b3ea-ab93165244cc.png)

**Comment by posva** [comment] 2022-05-27 14:59
Duplicate of https://github.com/vuejs/router/issues/701

**Closed by posva** 2022-05-27 14:59 UTC
