### ISSUE TITLE
Why is replace called once in the push method? In this way, both history.pushState and history.replaceState are triggered

### ISSUE THREAD

**Issue by kefaze** [vuejs/router#1659] opened 2023-01-10 09:06 UTC
### Version
4.1.6

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/ecstatic-cohen-yeyfcf)

### Steps to reproduce
1. Listen globally or override "pushState " and "replaceState"
2. Use the ”router.push“ method to switch routes

### What is expected?
The "router.push" method is expected to only trigger the "history.pushState"

### What is actually happening?

The "router,push" method triggers both " history.pushState " and "history.replaceState"

**Comment by posva** [comment] 2023-01-10 10:57
This has been answered before: https://github.com/vuejs/router/issues?q=is%3Aissue+sort%3Aupdated-desc+history.replaceState+is%3Aclosed

Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Comment by posva** [comment] 2023-01-10 10:57
Duplicate of https://github.com/vuejs/router/issues/1526

**Closed by posva** 2023-01-10 10:57 UTC
