### ISSUE TITLE
Cannot use scrollBehavior to scroll a non-body element

### ISSUE THREAD

**Issue by snoozbuster** [vuejs/router#1572] opened 2022-10-08 00:36 UTC
### Version
4.1.5

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/brave-chebyshev-ue9yrk?file=/src/router.js)

### Steps to reproduce
1. Open the reproduction link
2. Scroll down to the bottom of the page
3. Click the "About" link at the top

### What is expected?
4. The page scrolls back to the top

### What is actually happening?
4. The page does not scroll

---
When using a page layout scheme which involves a container element that is `height: 100vh` and a `router-view` contained within a child element that is `overflow: scroll`, `scrollBehavior` cannot be used to automatically scroll the element with `overflow: scroll` on navigation.

In the example, `#viewport` in `App.vue` is a layout element used to position a sticky header (and in our app, a sticky sidebar) and itself does not scroll. Its inner child `#content` is the element which scrolls in response to user input; however, using `el: '#content'` in scrollBehavior does not actually scroll the content in response to navigation.

This appears to be because the [function used](https://github.com/vuejs/router/blob/main/packages/router/src/scrollBehavior.ts#L146) to scroll the page is [`window.scrollTo`](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollTo) instead of [`Element.scrollTo`](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollTo) on the targeted element. In this example, the `window` never actually scrolls, due to the wrapping element being `100vh` - instead, it is the child `#content` element which handles all the scrolling.

**Comment by snoozbuster** [comment] 2022-10-08 00:39
Because this interface currently supports negative offset (which I don't think Element.scrollTo can do anything with), I am not sure if this is as simple as replacing the window.scrollTo with Element.scrollTo when the `el` option is given (or at least, such a change would require a minor version bump). That being said, I would love to contribute a fix for this if that or something similar would work - not sure if there is any reason why we need to use window.scrollTo when an `el` option is explicitly given.

**Comment by posva** [comment] 2022-10-08 15:35
Duplicate of https://github.com/vuejs/router/issues/1189#issuecomment-961157423

**Closed by posva** 2022-10-08 15:35 UTC
