### ISSUE TITLE
Documentation website Guide and API link won't always work

### ISSUE THREAD

**Issue by 6XGate** [vuejs/router#1817] opened 2023-04-25 17:39 UTC
### Reproduction

https://router.vuejs.org/

### Steps to reproduce the bug

1. Navigate to https://router.vuejs.org/
2. Click on Guide or API

### Expected behavior

Sent to Guide or API page.

### Actual behavior

Nothing occurs on site. In the dev tools, the following messages are seen:
```
Uncaught (in promise) TypeError: can't access property "scrollTop", e is null
    t https://unpkg.com/thesemetrics@latest:1
    i https://unpkg.com/thesemetrics@latest:1
    j https://unpkg.com/thesemetrics@latest:1
    pageread https://unpkg.com/thesemetrics@latest:1
    _ https://unpkg.com/thesemetrics@latest:1
    r https://unpkg.com/thesemetrics@latest:1
    i https://unpkg.com/thesemetrics@latest:1
    o https://router.vuejs.org/assets/app.abce5f04.js:1
    Sc https://router.vuejs.org/assets/app.abce5f04.js:1
    Sc https://router.vuejs.org/assets/app.abce5f04.js:1
    E1 https://router.vuejs.org/assets/app.abce5f04.js:8
    L1 https://router.vuejs.org/assets/app.abce5f04.js:8
    <anonymous> https://router.vuejs.org/assets/app.abce5f04.js:8
[thesemetrics@latest:1:665](https://unpkg.com/thesemetrics@latest)
    o https://router.vuejs.org/assets/app.abce5f04.js:1
    AsyncFunctionNext self-hosted:810
    (Async: async)
    Sc https://router.vuejs.org/assets/app.abce5f04.js:1
    (Async: EventListener.handleEvent)
    Sc https://router.vuejs.org/assets/app.abce5f04.js:1
    E1 https://router.vuejs.org/assets/app.abce5f04.js:8
    L1 https://router.vuejs.org/assets/app.abce5f04.js:8
    <anonymous> https://router.vuejs.org/assets/app.abce5f04.js:8
```

### Additional information

![Screenshot from 2023-04-25 12-35-02](https://user-images.githubusercontent.com/5586463/234357927-71467c68-8a87-452b-b1da-f68b1a7d075f.png)

**Comment by posva** [comment] 2023-04-25 22:23
Duplicate of https://github.com/vuejs/router/issues/1784

**Comment by posva** [comment] 2023-04-25 22:23
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed by posva** 2023-04-25 22:23 UTC
