### ISSUE TITLE
Provide self-contained vue-router ESM production build

### ISSUE THREAD

**Issue by roeltz** [vuejs/router#1658] opened 2023-01-09 17:24 UTC
### What problem does this feature solve?
I'm trying to develop an application with a CDN approach to dependencies, and while the ESM production build for Vue itself works as expected without complications, VueRouter's ESM browser build is not a minfied resource and makes requests for many more dependencies (which also need an additional importmap entry for @vue/devtools-api). I've tried the global build vue-router.global.prod.js (even with some modifications on top), but the workarounds needed to make it work defeat the purpose of having an ESM-only architecture in the first place.

### What does the proposed API look like?
For this, it would be ideal to have a proper production build, without any dependencies or instrumentation for DevTools (or have them inlined in the bundle), with a size comparable to that of vue-router.global.prod.js

**Comment by posva** [comment] 2023-01-09 20:28
Duplicate of https://github.com/vuejs/router/issues/694

**Comment by posva** [comment] 2023-01-09 20:29
Unfortunately, given the existing restrictions for importing other packages, this won't be doable. Instead, one has to rely on solutions like skypack

**Closed by posva** 2023-01-09 20:28 UTC
