### ISSUE TITLE
In History mode sending more than one parameters breaks page refresh

### ISSUE THREAD

**Issue by Dagge11** [vuejs/router#2079] opened 2023-12-14 12:22 UTC
### Reproduction

Vue 3 / Vue Router 4 / Nodejs

### Steps to reproduce the bug

When I am in history mode in Vue3/Router 4 and try to send more than one parameter via _router link_, after I try to refresh a new page it shows random JSON data contained on this page instead of an actual page. When sending one parameter only, refreshing the page works properly and displays desired page.

### Expected behavior

History mode should refresh page properly by accepting more than one parameter sent via router link

### Actual behavior

Wrong

**Comment by posva** [comment] 2023-12-14 12:39
Duplicate of https://github.com/vuejs/router/issues/1928 and others. Likely related to this https://github.com/vuejs/router/blob/main/packages/router/CHANGELOG.md#important-note.

Please don't open issues without searching first or without a reproduction.

**Closed by posva** 2023-12-14 12:39 UTC
