### ISSUE TITLE
Automatic inheritance of optional parameters

### ISSUE THREAD

**Issue by lermontex** [vuejs/router#1697] opened 2023-02-14 23:12 UTC
### What problem does this feature solve?
I recently ran into an issue:: #1682

As it turns out, this behavior is not a bug.

I suggest adding a way to allow automatic inheritance of optional parameters as the proposed solution does not solve the issue.

```
router.beforeEach((to, from) => {
  if (!to.params.locale && from.params.locale) {
    return { ...to, params: { ...to.params, locale: from.params.locale }}
  }
})
```

As I wrote earlier, this option is not suitable for sites where rendering takes place on the web server side, since links will be generated without taking into account the locale parameter.

```
example.com/page instead of example.com/en/page
```

It turns out that the only solution would be to set the parameter manually (in the current project I have more than 550 links)

P.S. If I make the `locale` parameter required, I won't be able to make the primary language of the website available without specifying the locale (as recommended by SEOs)

```
example.com/ - default locale
example.com/en/- other locale
```

### What does the proposed API look like?
Perhaps an additional configuration parameter will help solve this issue?

**Comment by posva** [comment] 2023-02-15 08:28
If you want to have a fallback, just add one. It can be in a navigation guard:

```ts
router.beforeEach((to, from) => {
  if (!to.params.locale) {
    return { ...to, params: { ...to.params, locale: from.params.locale || 'en' }}
  }
})
```

Or using a `computed()` or a fallback wherever you pass the locale to:

```ts
const i18n = VueI18n.createI18n({
  locale: 'ja', // set locale
  fallbackLocale: 'en', // set fallback locale
  // ...
})
```

From https://vue-i18n.intlify.dev/guide/

Or handled where you handle the i18n so you can keep URLs without the locale parameter but that is outside of vue router scope.

**Comment by posva** [comment] 2023-02-15 08:28
Duplicate of https://github.com/vuejs/router/issues/1682

**Closed by posva** 2023-02-15 08:28 UTC
