### ISSUE TITLE
`useRoute().params.param` evaluates to `undefined` on navigation from `/:param` to `/` when using nested `<router-view />`

### ISSUE THREAD

**Issue by DrJume** [vuejs/router#1629] opened 2022-12-09 18:27 UTC
### Version
4.1.6

### Reproduction link
[stackblitz.com](https://stackblitz.com/edit/vitejs-vite-qd21wy?file=src%2Fmain.ts,src%2FHome.vue,src%2FParam.vue&terminal=dev)

--> Open in New Tab and open Console in DevTools.

### Steps to reproduce
1. Use router with subroutes under a nested RouterView (from 'vue-router')
```ts
{
  path: '/routerView/',
  component: RouterView,
  children: [
    {
      path: '',
      component: Home,
    },
    {
      path: ':param',
      component: Param,
    },
  ],
},
```
2. Watch `useRoute().params.param` inside `Param.vue`

### What is expected?
Watching `useRoute().params.param` does not trigger when going from `/routerView/123` to `/routerView`.

### What is actually happening?
`useRoute().params.param` evaluates to `undefined` when navigating from `/routerView/123` to `/routerView`.

### Additional comments

When a nested `<router-view />` (`component: RouterView`) isn't used, it works as expected.

**Comment by posva** [comment] 2022-12-10 10:54
Normally, one wouldn't put the `RouterView` in the `component` option, it should just be omitted and it will work. Did you find any outdated documentation showing to use `RouterView` like that?

**Comment by DrJume** [comment] 2022-12-10 16:10
I know, it used to be necessary, but I just wanted to demonstrate that the issue only happens when using a nested RouterView.
To keep it minimal I used RouterView directly, not using it inside <template> of e.g layout component.

**Comment by DrJume** [comment] 2022-12-10 16:11
This is a real issue happening in a application, where 2-3 nested layouts are used.

**Comment by posva** [comment] 2022-12-10 20:01
Duplicate of https://github.com/vuejs/core/issues/7030

**Closed by posva** 2022-12-10 20:02 UTC
