### ISSUE TITLE
Provide a way to disable warnings for "No match found"

### ISSUE THREAD

**Issue by hokkaido** [vuejs/router#1828] opened 2023-05-03 07:57 UTC
### What problem is this solving

At the moment, the router logs a "No match found" warning that cannot be disabled when it tries to resolve a route that doesn't exit. 

There are more complex routing scenarios where the creation of initial routing table or the addition of a new route requires a check whether a route already exists, by calling the router instance's resolve method. The warning impairs the development cycle by polluting the log (both on client and server in an SSR context).

As an example, think of an SSR app with a backend where admin users can create additional redirects or aliases to hardcoded routes in the administration panel.

### Proposed solution

Add a flag, disableWarnings, in the createRouter factory method to disable these kinds of warnings.

**Comment by posva** [comment] 2023-05-03 09:40
Duplicate of https://github.com/vuejs/router/issues/359

**Comment by posva** [comment] 2023-05-03 09:40
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed by posva** 2023-05-03 09:40 UTC
