### ISSUE TITLE
Why 'router.push' will execute 'history.replaceState' and 'history.pushState' ?

### ISSUE THREAD

**Issue by HJM515** [vuejs/router#1529] opened 2022-08-24 09:28 UTC
### Version
4.1.4

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/quizzical-williamson-nrwrqg)

### Steps to reproduce
1. Open https://codesandbox.io/s/quizzical-williamson-nrwrqg
2. Click on About Link
3. Check console

### What is expected?
Expected only console 'pushState'

### What is actually happening?
console 'replaceState' and 'pushState'

---
Our web track sdk try rewrite pushState and replaceState to record pv. SDK is used by Vue2, Vue3, React projects.
When SDK is used in Vue3 projects,  'router.push' will execute 'history.replaceState' and 'history.pushState', and our pv records wil be wrong.  Vue2 projects don't have this problem.

**Comment by posva** [comment] 2022-08-24 10:01
Duplicate of https://github.com/vuejs/router/issues/1416

**Closed by posva** 2022-08-24 10:01 UTC

**Comment by posva** [comment] 2022-08-24 10:09
Note `history.replaceState()` can be called to change the state of the current history entry and therefore doesn't always means navigation. This behavior can also be manually done by users.
