### ISSUE TITLE
Specify scrollable element for scroll behavior

### ISSUE THREAD

**Issue by Calneideck** [vuejs/router#1609] opened 2022-11-12 02:05 UTC
### What problem does this feature solve?
The savedPosition prop of scrollBehavior gets its left/top values from the window. This is an issue for pages where the main scrollable area is on another element and not the body. In these cases it will always return (0,0) making it impossible to get the last known scroll position.

### What does the proposed API look like?
It would be great to have an optional element or id selector to pass into createRouter which is used in computeScrollPosition to save the scroll position of the specified element.

**Comment by posva** [comment] 2022-11-12 07:48
Duplicate of https://github.com/vuejs/router/issues/1189#issuecomment-961157423

**Closed by posva** 2022-11-12 07:48 UTC
