### ISSUE TITLE
router4.x is not available in Vue2.7. There is no userouter, so how can router be used in Vue2.7 setup

### ISSUE THREAD

**Issue by zzzz-Z** [vuejs/router#1462] opened 2022-07-08 10:46 UTC
### Version
4.1.1

### Reproduction link
[codepen.io](https://codepen.io/chun2670/pen/ROGebo)

### Steps to reproduce
https://codepen.io/chun2670/pen/ROGebo

### What is expected?
https://codepen.io/chun2670/pen/ROGebo

### What is actually happening?
https://codepen.io/chun2670/pen/ROGebo

---
router4.x is not available in Vue2.7. There is no userouter, so how can router be used in Vue2.7 setup

**Comment by posva** [comment] 2022-07-08 13:25
Duplicate of https://github.com/vuejs/vue-router/issues/3760

**Closed by posva** 2022-07-08 13:25 UTC
