### ISSUE TITLE
About adding nested routes

### ISSUE THREAD

**Issue by caseor** [vuejs/router#1430] opened 2022-06-02 03:41 UTC
### Version
4.0.15

### Reproduction link
[jsfiddle.net/0j1yLecx/2/](https://jsfiddle.net/0j1yLecx/2/)

### Steps to reproduce
When add nested routes to an existing route
```js
const router = createRouter({
  history: createWebHistory(),
  routes: [
    { path: '/', redirect: '/foo' },
    { name: 'root', path: '/foo',  component: Foo }
  ],
})
console.log('hasRoutes: ', router.hasRoute('root'))
router.addRoute('root', { name: 'aaa', path: '/bar', component: Bar })
console.log('routes: ', router.getRoutes())
```

### What is expected?
route 'aaa' append to the root's children list.  
router.getRoutes():  
{ name: 'root', path: '/foo',  component: Foo, children:[{ name: 'aaa', path: '/bar', component: Bar }]}

### What is actually happening?
but 'aaa' not added to the root's children list.  
router.getRoutes():  
{ name: 'root', path: '/foo',  component: Foo, children:[]}

**Comment by posva** [comment] 2022-06-02 13:15
Duplicate of https://github.com/vuejs/router/issues/600

**Comment by posva** [comment] 2022-06-02 13:15
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed by posva** 2022-06-02 13:15 UTC
