### ISSUE TITLE
Route component receives updated `$route` before navigating to a different route

### ISSUE THREAD

**Issue by zenflow** [vuejs/router#1432] opened 2022-06-06 21:20 UTC
### Version
4.0.15

### Reproduction link
[jsfiddle.net/xr1g8uyj/](https://jsfiddle.net/xr1g8uyj/)

### Steps to reproduce
1. Go to minimal reproduction
2. Click "Foo" link
3. Observe message in console: "Foo received changed $route: from /foo?editor_console=true to /foo" (Good!)
4. Click "Bar" link
5. Observe message in console "Foo received changed $route: from /foo to /bar" (Bad!)

### What is expected?
I expected that the second console message would not be printed.
I expected that a route component would not receive a `$route` object that doesn't match the component's route.
This is how vue-router v3 (for Vue 2) worked.

### What is actually happening?
Actually the second console message ("Foo received changed $route: from /foo to /bar") *is* printed.
Before the old route component is unmounted, it receives an updated `$route` object that matches the *next* route (but not the route of the currently mounted component)

---
In our large application that we're upgrading to Vue 3 & vue-router 4, we watch `$route` to fire certain side-effects  (e.g. fetching data based on query parameters, replacing route with normalized query parameters when necessary, etc).
All of this relies on the expectation that the $route object in a route component matches the route of that route component.
Without this expectation being met, we are getting various errors and bugs.

**Comment by posva** [comment] 2022-06-08 12:57
Duplicate of https://github.com/vuejs/router/issues/1381

**Closed by posva** 2022-06-08 12:57 UTC
