### ISSUE TITLE
keeplive in three router have problem setup will execute more times

### ISSUE THREAD

**Issue by Miofly** [vuejs/router#1662] opened 2023-01-12 05:02 UTC
### Version
4.1.6

### Reproduction link
[github.com](https://github.com/Miofly/vue-keep-alive-issue)

### Steps to reproduce
click route see console

### What is expected?
keepalive correct and setup do not execute more times

### What is actually happening?
yes

---
vue2 is correct

**Comment by posva** [comment] 2023-01-12 08:05
Duplicate of #626

**Comment by posva** [comment] 2023-01-12 08:06
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed by posva** 2023-01-12 08:05 UTC
