### ISSUE TITLE
Children are not added to parent record on addRoute

### ISSUE THREAD

**Issue by ryanz69** [vuejs/router#1684] opened 2023-02-03 11:21 UTC
### Version
4.1.6

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/wonderful-tristan-v9oecp)

### Steps to reproduce
click on "test new route" btn and open console for show data return with router.getRoutes().

### What is expected?
new route is added to children home route

### What is actually happening?
new route is not added to children home route

**Comment by posva** [comment] 2023-02-03 14:04
Duplicate of https://github.com/vuejs/router/issues/600

**Comment by posva** [comment] 2023-02-03 14:04
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed by posva** 2023-02-03 14:04 UTC
