### ISSUE TITLE
There's a bug in vue-router v4.4.3

### ISSUE THREAD

**Issue by yfttgdzy** [vuejs/router#2344] opened 2024-08-26 01:56 UTC
### Reproduction

https://play.vuejs.org/#eNqlVt1u2zYUfhVOHWC5iyXHDXqhKUbaIFs2tF3QDruZdiFLx7ISiSRIKnFh+N13SEqUlNgJ2iJwTJ7/jx/PoXdenZY0uJVe5JU1Z0KRHckEpArecU72ZC1YTSb3DUwS6gwEaxQIpw1CK+hNtG+nSzkPrH9CXWQfP9OEEhI0Enzrbvc1a6jyJ6/QbTL1TrzWHeuLFdS8Qv+lNow3p8trqCqmk/0Uh7g1Ym6+cCGVYLRYXjZCAFW2ZsJTtYnisNWR3Y78bBTBuqmqG1SS/d6ECW2cmKb3XcDPpsoPJb0jip0nXph4y98Zrsk1qyEOe/1Rj3SFEuf2Tu+e+MVhlzPW3Ixj/VPCAwlbu1Ydh+5g8LzsWQbqAKMfoWbi63UpFX6dtEIbd8j0zLHp+NQATeqO1E7QMtvRrgGN7JzEXYGEwtYYZ4zKlhZBzkfV+DsNcGMLjQ5V709PtInxlhH51x7SzvJLJuEE4TEsiiL1UV/+3ngNDQ0jY+sehTX/D//v8XImtD3bFayZgKs02/j+lJzjNXKqNM8NBIugS5Ix+JCKAr4gEqATE5WmNaDuktV2PyjABrVn6uMhXo7czUlq+Lqmg2n7xJFe+MHr6WubxKW9SQv4xNRv2Gx5p3qmgishmHCJtXENKo00cL0hRJWq0nGNoQ7eBdU05vAeGcwz0dSriCjRwEj5EWgzEncsZZuyyrF5Hb9IXLd4DuMLOL8Z6wG8L2B+EfdR7EP8/UpfQdxNf8URim3DKggqVrRzMyhAGfalP9UWpjFANYKawPai4GQY9qwepzITJVdEoiknVUoLnFBK4nTSI8UqcYmbR3N3sewi4dRdPBlAo5b/sTwu1MFElrJZnXJ8vxjFVIaepFVgBkdY4vVzTYsTb6MUl1EYNpTfFQFeh7C3uDgLzoI3YY6jZiANQNazlWAPEte3GL3lJvEu0CjM4V4xVslZystjKZ4YXrwN3ganYVWuQoweljSHrYlt6EbmEKaSSPm6LB6B1De4rED8xVWJV2IENsVn8eFPIxtcLfTZQHZ3QH4rt7bkGwGI7h4G4JSePPhmafXVl0+wxbVT1ixvKrR+RvkZ8Lo2ukZr9h47Ecse2Jlq/zCclbT4W15tFVDZgbJXuGsFQyTOzKPQ+3LfBGeDU5TqawUyyKR+F/GBPSH69bR+KyZyEBFZ8C3BYsucvJrP59hJ2PYYrqSzFVOK1RE5nfOtkXOcuFisk2CWhGJYsiQp+QU/JnDrXcEa58zQcrMYZu7D9wVkWTYoICJz/Fu0ERDO0yfhcactn+utvOx+1YwD2d8VVjtoNjM+3Fz8zkzG/3iC/f8m6nda

### Steps to reproduce the bug

Sorting rule error

### Expected behavior

![4D77923D-C323-476d-A43D-0A88113556F5](https://github.com/user-attachments/assets/5644c399-9a9f-4bad-846d-e1704da6ffe7)

### Actual behavior

Problems with routing CoeLargeScreen sorting

**Comment by posva** [comment] 2024-08-26 06:44
Duplicate of #2266

**Closed by posva** 2024-08-26 06:44 UTC

**Comment by posva** [comment] 2024-08-26 06:48
In your case, the `children` can be completely removed:

```js
router.addRoute({
    path: '/:path(.*)*',
    name: 'PageNotFound',
    component: () => import('./Error.vue'),
    meta: {
      title: 'ErrorPage',
      hideBreadcrumb: true,
      hideMenu: true,
    },
  });
```
