### ISSUE TITLE
When using nested RouterView and KeepAlive, components aren't detached properly

### ISSUE THREAD

**Issue by CrimsonFez** [vuejs/router#2314] opened 2024-07-28 20:37 UTC
### Reproduction

https://github.com/CrimsonFez/vuejs-keep-alive-router-bug/

### Steps to reproduce the bug

You need to have nested RouterView + KeepAlives like:  

App.vue
```
<RouterView>
  <KeepAlive>
    <Component>
```

MyLayoutAndGetter1.vue
```
<RouterView>
  <KeepAlive>
    <Component :my-object="my-object">
```

MyLayoutAndGetter2.vue
```
<RouterView>
  <KeepAlive>
    <Component :my-object="my-object">
```

I believe that you also need to pass props through one of the router views, see https://github.com/CrimsonFez/vuejs-keep-alive-router-bug/blob/main/src/views/Person.vue  

See my linked repo for full reproduction.

### Expected behavior

This should behave like normal, when KeepAlive is not used

### Actual behavior

When changing from one nested routerview to the other, it looks like props from the old router view are temporarily attached to the new router view
```
[Vue warn]: Missing required prop: "region" 
  at <RegionAbout onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< null > person= 
Object { id: "gandalf", name: "Gandalf", summary: "2000 year old pot smoking wizard" }
  ... > 
  at <KeepAlive key=0 > 
  at <RouterView key=0 > 
  at <Person personId="gandalf" onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< null >  ... > 
  at <KeepAlive key=0 > 
  at <RouterView> 
  at <App>
```
In my reproduction, this just causes an error, but on my larger app, this causes a crash.

**Comment by CrimsonFez** [comment] 2024-07-28 21:12
For anyone else with this issue, I found a work around. Give the 2nd level routerviews each a unique name, then in router.ts set that as the view for your child components.

**Comment by posva** [comment] 2024-07-29 08:10
Duplicate of #626

**Closed by posva** 2024-07-29 08:10 UTC

**Comment by posva** [comment] 2024-07-29 08:17
Some of this behavior is inherent to KeepAlive and how it keeps updating components that are kept alive. [Check this Vue playground](https://play.vuejs.org/#eNq9VE1v2zAM/SucLs5QIxmwnYKkW9cVWDdgLboCu/ji2vRH60iGJCcF0vz3kZLsOEXQbjvsEMQi+chH8klbcda203WHYi4WJtN1a8Gg7drTRNarVmkLW9BYxNBqta5zjMFUadOozQ0WsINCqxVEhI8SCRAQVxKDYzqjb04/dt9u1OCm7+BOZKaksbAyJSy55CT6ilQIfind5G+it32ADO53ZAmkJlGmOmlRRzFIMgPwz4e3aYmE2LOeECUXU3Qys7WSYFVZNnhNgZO3sGUXONh0nTYdg8eH5dL199G1MedvBuz6ogMjxhAd/qNqi5kfLo2VDhZXbZNapBPAgmfNJc+rVBJXRziVOe0BoVIbb8ic08AdFkojKPkFU2K/piw5sbYVSqhlpnGF0jp4VmH2wA43CNXg1FWb+XKLu85a6v1T1tTZwzIR8uQkEYHJZZ/II3yo8zlDpY+n2M9xyDTq6Xiu74jtWVOv/SzIkClSieQm5rWhpA4qYOZLzsbxi9kwSBGLoLSXhFzLe8xsfDg9Pp7tD5vUZtUzZY+l53PsFTfoMgit97v9kzORh7uiZS1Pvcr6vTSqnET5PoZhO/o5KhNORDo6jhppI2e1MTKmToumM9UcolYZGwEnG9TOuCDzg1Ssao0yRx0Y/JlqLyXfgTnIOWy3IfnTE41q5+7EK0p7prVnCvFiPVxzeDFeX/Pf7fDV8fB1/7fxEPL/jccaYl3U5fTeKElDco0kgm9V3aC+arlJkwii4zMmwj2M35zN6g7j3u4ekCP2e/PItkRcazSo13Q9B59NdYnWuy9+/sBH+h6cK5V3DUW/4LxBmnjHHH3Y507mRHsU59heulXXsrw1F48WpembYqLuPXbxiaDdn7/Q+p7u++mH8I7vxO43JBBbYw==) to give you an idea of the behavior:

- Change page twice
- click increment
- Both components keep updating in the background
