### ISSUE TITLE
useRoute().params in typescript

### ISSUE THREAD

**Issue by dongnaebi** [vuejs/router#1585] opened 2022-10-20 16:34 UTC
### Version
4.1.5

### Reproduction link
[github.com](https://github.com/vuejs/router/issues/new/choose)

### Steps to reproduce
```typescript
setup () {
    const route = useRoute()
    const id: string = route.params.id
}
```

### What is expected?
got a type error
```
TS2322: Type 'string | string[]' is not assignable to type 'string'.   Type 'string[]' is not assignable to type 'string'.
```

### What is actually happening?
type error

---
export a useParams method or add generic for useRoute

**Comment by dongnaebi** [comment] 2022-10-20 17:04
sorry I just find a same issue: https://github.com/vuejs/router/issues/1160

so, any plan for this?

**Comment by posva** [comment] 2022-10-20 17:43
Duplicate of #1160

**Comment by posva** [comment] 2022-10-20 17:43
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed by posva** 2022-10-20 17:43 UTC
