### ISSUE TITLE
Route update unexpectedly triggers watchers

### ISSUE THREAD

**Issue by lwansbrough** [vuejs/router#2022] opened 2023-10-19 00:00 UTC
### Reproduction

https://jsfiddle.net/sj1chxmd/2/

### Steps to reproduce the bug

Observe behaviour in this repro (Vue 2.7): https://jsfiddle.net/sj1chxmd/2/
Then compare the behaviour in this repro (Vue 3): https://jsfiddle.net/sf2gutkr/1/

### Expected behavior

The behaviour should be the same between the two examples.

### Actual behavior

The presence of a reactive variable on the `<router-view>` in the Vue 3 version forces its descendants' watchers to update. I believe the correct behaviour should be the Vue 2.7 behaviour.

### Additional information

Related:

- https://github.com/vuejs/vue-router/issues/3393
- https://github.com/vuejs/router/issues/1590

**Comment by posva** [comment] 2023-10-19 07:10
Duplicate of https://github.com/vuejs/core/issues/7030

**Closed by posva** 2023-10-19 07:11 UTC
