### ISSUE TITLE
Partial child Route Loss

### ISSUE THREAD

**Issue by MyPledge** [vuejs/router#2312] opened 2024-07-24 02:46 UTC
### Reproduction

https://play.vuejs.org/#__PROD__eNqlVW1v2zYQ/iucOsAOFouOF/SDphpZi2LZsJeiK/qlCgpZOttsJJIgKduF4f/eI6kXOrGDorFhS7yX5+7I5477qM4Zj7/oKIlYLYUyZE8KBbmB36UkB7JUoiajTQOjjLcGSjQGVKuJqV8OauvX6XIpY++b8R51jL+LjBMSNxrG3t2va9FwMx69QLfRRXQZte6YW2qglhX6z61hur6a30JVCRvsp5Ti0omle+CLNkrw1fxNoxTwNmMic7NOUtrqyH5PfnaKeNlU1TtUksPBwVCPk/J80wG+d1n+zfg9MeJVFtG8rBn3tfv/z/lCbCCL5n8INPEhvSylg/f34x0j/RjG5wVUYotIweoRUkq7OlPLhWP0jwy2hLZ2rTql/WHgGfnzO8mgf6AW6ust0wYfl63Q44bMmvQM6jl0K2pwoTsidYKWTR3VFuh5ZNdLHhluIDTawLHBa7s1vYFbDcQVXLcc0uQV+WQ3Y+/ZREZ0hIUJBOFItGRI/HDpzPxmdrbugNDBS4s1q0rkZ+Ih7WffqgInF7f3sR+e1zAoBvkJPIcZLo5hPT9DjIf4py2Cgt1ehlpf+HcEfyrs0wH9Cf9QUN8DD+HDgk8aBPEdN87FvuuPqZPe2QeOFXweMUkhk8KGGLuk175XklMNNL5wkJ6H+HrAmZnxLeOl2H7yyavRHcL614zDzlG7hGXeVF1Y7Niwl+xo1YVi0hANppGkyvkKZ4nRODVsq3slvuLiwQyezTsknMCzR4PhqBWfF8dt0dlAvoUndS5xCgmOodxeZq0CIyQdJbJomDdWnEVrY6ROKG24vF/FeM50sLi5jq/jKS1x/wNpDLqeLJTYajf2sqg96Sy6QSNawsYIUelJLtm5EI8Mb17GL+MrWrEFRXSKZwo7h92y54BlGo30WbLVgyItNVkF6j9pGNLrqNgcr8jtX05mVAN9osUaivsT8i9651N+pwCrs9dZrzO5WoHx6rf//ws7fO+VtSibCq2fUL4HLarG5ujNXje8xLQDO5ftn+7MGF990G93BrjuirKJut1w9u4g3zxR+pDur/F1sIvafK1Ax4W29xVefJfE3mrebyFUCSohM7kjmCwryYvpdPqbVdUIx/hkIYwRdUKupnLn5DIvS0y2l2CUjCMsmZOc/II/B9x6V7DEARJarmdh5AF+SKAoiiCBhEzxO2sRfJP5q+x5DeZgzjZYfx0+L4iDORPk8A0H927O

### Steps to reproduce the bug

![image](https://github.com/user-attachments/assets/d3bd3e71-fe23-42ca-99e5-45e188b72f52)
Click to view separately.

### Expected behavior

All three pages should display correctly.

### Actual behavior

If the child route name is the same as the parent route name, the routes defined before this child route will be lost.

**Comment by posva** [comment] 2024-07-24 07:24
Duplicate of #2266

**Closed by posva** 2024-07-24 07:24 UTC
