### ISSUE TITLE
v4 breaking change: watchers on $route.query triggered on route change

### ISSUE THREAD

**Issue by taobojlen** [vuejs/router#1381] opened 2022-04-26 08:57 UTC
### Version
4.0.14

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/blissful-water-umyk2l?file=/src/App.vue)

### Steps to reproduce
1. Create a watcher on `$route.query` in a component that's only rendered on one route.
2. Notice that the watcher is triggered when navigating to another route.
3. If you do the same with Vue 2 / vue-router v3, the watcher is not triggered.

### What is expected?
The behaviour is the same as vue-router v3.

### What is actually happening?
The behaviour changed!

---
We have a very common pattern of a watcher on `$route.query` that fetches data when the URL query changes. Now, because of this change, our app makes many more unnecessary network requests when navigating to different routes.

One potential workaround is to set some global state, like `isUnmounting = true`, in the router's global before hook (and then unset it in the after hook). Then, we could return early in the watchers if this boolean is true. However, this isn't a very clean solution!

**Comment by posva** [comment] 2022-04-26 12:44
Duplicate of https://github.com/vuejs/core/issues/2291 for when leaving a route.

**Closed by posva** 2022-04-26 12:44 UTC
