### ISSUE TITLE
Scoped styling is not applied to child of RouterLink slot (aka missing v-data-{id})

### ISSUE THREAD

**Issue by mkarras** [vuejs/router#1641] opened 2022-12-23 07:31 UTC
### Version
4.1.6

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/scoped-styling-not-applied-to-router-link-child-3vst0s?file=/src/views/Home.vue)

### Steps to reproduce
`vue-router`: `4.1.6`
`vue`: `3.2.45`
`@vitejs/plugin-vue`: `4.0.0`

Using a custom link component:

_LinkComponent.vue_
```
<template>
   <RouterLink custom ...>
      <a ...><slot /></a>
   </Routerlink>
</template>
```

In parent:
```
<template>
    <LinkComponent class="custom-styling">my link</LinkComponent>
</template>

<style lang="postcss" scoped>
   .custom-styling {
       @apply whatever;
    }
</style>    
```

### What is expected?
The scoped styling should be applied to anchor element of `LinkComponent`. `data-v-{id}` should be present at anchor element.

### What is actually happening?
The styling has no effect because of missing scoping (`data-v-{id}`) at the anchor element of `LinkComponent`. 

---
Worked in vue 2 (`"vue": "~2.6.14"`, `"vue-router": "^3.5.1"`, `"vue-template-compiler": "~2.6.14"`, `"vite-plugin-vue2": "^2.0.2"`), before upgrading to vue 3 and vue-router 4.

I posted this already in https://github.com/vuejs/router/issues/291#issuecomment-1362519542 but the issue was closed because of another. It was mentioned that vite does not depend on vue-loader. So im not sure if this is really a bug in vue-loader, but vue-router.

**Comment by posva** [comment] 2022-12-24 15:50
Duplicate of https://github.com/vuejs/core/issues/5234

**Closed by posva** 2022-12-24 15:50 UTC

**Comment by mkarras** [comment] 2022-12-24 21:43
Hi @posva i updated the [codesandbox](https://codesandbox.io/s/scoped-styling-not-applied-to-router-link-child-3vst0s?file=/src/components/NoLinkComponent.vue) with another component not using RouterLink, and scoped styling works like a charm.

Looking like this:
```
<template>
  <div v-bind="$attrs">I'm a simple component and scoped styling works</div>
</template>

<script>
export default {
  name: "NoLinkComponent",
  inheritAttrs: false,
};
</script>
```

I also removed the `inheritAttrs` from `LinkComponent` without any change. The anchor element is the first and only child of RouterLink. RouterLink should provide the attrs also without `v-bind="$attrs"` when `inheritAttrs: true` like it did in vue-router 3 .

Please check this out a reopen the issue if you see it that way too.
It seems like that this is not related to https://github.com/vuejs/core/issues/5234
