### ISSUE TITLE
useRoute is undefined when following vue-test-utils guide to test with Composition API

### ISSUE THREAD

**Issue by wbiller** [vuejs/router#1466] opened 2022-07-10 22:40 UTC
### Version
```
>= 4.1.0
```

### Reproduction link
[github.com](https://github.com/wbiller/vue-router-mock-test/)

### Steps to reproduce
```
yarn
yarn test
```

### What is expected?
useRoute should be mocked and return the mocked value

### What is actually happening?
useRoute is undefined

---
When following the guide on vue-test-utils how to test vue-router with Composition API (see https://test-utils.vuejs.org/guide/advanced/vue-router.html#using-a-mocked-router-with-composition-api), the test fails.
The reason for that is that useRoute is undefined. The last version where it's working like described is 4.0.16.

**Comment by rros** [comment] 2022-07-13 10:52
Yes, it seems related. We have this issue with version 4.1+ of vue-router. Using the latest version, the following mocks make the tests fail

```
vi.mock('vue-router', () => ({
  useRoute: () => ({
    query: { pageNumber: 1 },
  }),
}));
```

When changing the mocks like this, the tests will succeed again.
```
vi.mock('vue-router/dist/vue-router.mjs', () => ({
  useRoute: () => ({
    query: { pageNumber: 1 },
  }),
}));
```

So, the workaround is to mock the .mjs version until https://github.com/vitejs/vite/issues/8659 has been fixed

**Comment by Machineric** [comment] 2022-09-06 06:00
> Yes, it seems related. We have this issue with version 4.1+ of vue-router. Using the latest version, the following mocks make the tests fail
> 
> ```
> vi.mock('vue-router', () => ({
>   useRoute: () => ({
>     query: { pageNumber: 1 },
>   }),
> }));
> ```
> 
> When changing the mocks like this, the tests will succeed again.
> 
> ```
> vi.mock('vue-router/dist/vue-router.mjs', () => ({
>   useRoute: () => ({
>     query: { pageNumber: 1 },
>   }),
> }));
> ```
> 
> So, the workaround is to mock the .mjs version until [vitejs/vite#8659](https://github.com/vitejs/vite/issues/8659) has been fixed

I've been searching for this issue and workaround for the past few hours! 
thanks for the tip!

**Comment by dannybster** [comment] 2022-09-29 13:57
> Yes, it seems related. We have this issue with version 4.1+ of vue-router. Using the latest version, the following mocks make the tests fail
> 
> ```
> vi.mock('vue-router', () => ({
>   useRoute: () => ({
>     query: { pageNumber: 1 },
>   }),
> }));
> ```
> 
> When changing the mocks like this, the tests will succeed again.
> 
> ```
> vi.mock('vue-router/dist/vue-router.mjs', () => ({
>   useRoute: () => ({
>     query: { pageNumber: 1 },
>   }),
> }));
> ```
> 
> So, the workaround is to mock the .mjs version until [vitejs/vite#8659](https://github.com/vitejs/vite/issues/8659) has been fixed

Been looking for this for hours, thanks!! If you have a minute could you please explain why this works?

**Comment by awacode21** [comment] 2022-10-04 15:23
I am experiencing the same problem, but not with mocked router. I experience it with real router. When i follow these instructions:
https://test-utils.vuejs.org/guide/advanced/vue-router.html#using-a-real-router-with-composition-api

for me 
```
const route = useRoute();
const router = useRouter();
```

both always are undefined. i am trying to fix this the whole day. Without success. Now i found this ticket here, but it is related to mocked router, how a solution for real router could look like? Any idea? Cause i am quite desperate on this since hours.

**Comment by awacode21** [comment] 2022-10-04 15:27
Well i adpated your approach and adjusted my imports from
`import { createRouter, createWebHistory } from 'vue-router';`
to
`import { createRouter, createWebHistory } from 'vue-router/dist/vue-router.mjs';`

Then it is also working for the "real router" approach.

**Comment by awacode21** [comment] 2022-10-04 15:50
Well i adpated your approach and adjusted my imports from
`import { createRouter, createWebHistory } from 'vue-router';`
to
`import { createRouter, createWebHistory } from 'vue-router/dist/vue-router.mjs';`

Then it is also working for the "real router" approach.
Thank you so much for the workaround. This was driving me nuts.

**Comment by lielgut** [comment] 2023-03-05 09:04
> Yes, it seems related. We have this issue with version 4.1+ of vue-router. Using the latest version, the following mocks make the tests fail
> 
> ```
> vi.mock('vue-router', () => ({
>   useRoute: () => ({
>     query: { pageNumber: 1 },
>   }),
> }));
> ```
> 
> When changing the mocks like this, the tests will succeed again.
> 
> ```
> vi.mock('vue-router/dist/vue-router.mjs', () => ({
>   useRoute: () => ({
>     query: { pageNumber: 1 },
>   }),
> }));
> ```
> 
> So, the workaround is to mock the .mjs version until [vitejs/vite#8659](https://github.com/vitejs/vite/issues/8659) has been fixed

This solution actually doesn't work for me.
I get the following error when changing the import: "Could not find a declaration file for module 'vue-router/dist/vue-router.mjs"
anyone managed to solve this issue??

**Comment by sebapastore** [comment] 2023-10-12 19:22
> Yes, it seems related. We have this issue with version 4.1+ of vue-router. Using the latest version, the following mocks make the tests fail
> 
> ```
> vi.mock('vue-router', () => ({
>   useRoute: () => ({
>     query: { pageNumber: 1 },
>   }),
> }));
> ```
> 
> When changing the mocks like this, the tests will succeed again.
> 
> ```
> vi.mock('vue-router/dist/vue-router.mjs', () => ({
>   useRoute: () => ({
>     query: { pageNumber: 1 },
>   }),
> }));
> ```
> 
> So, the workaround is to mock the .mjs version until [vitejs/vite#8659](https://github.com/vitejs/vite/issues/8659) has been fixed

This workaround works if you are using certain versions of vitest. For example, in the "reproduction link" the version ^0.18 of vitest is used. The example works, with the workaround described, until version ^0.23 of vitest. Since version 0.24 of vitest, the workaround doesn't work anymore and the result of `useRoute()` is undefined.

**Comment by jesseice** [comment] 2024-01-10 10:46
Will the vue version downgrade to 3.3.4 can use the specific source code what wrong do not know

**Comment by posva** [comment] 2024-02-15 14:53
This seems to be now resolved with the latest versions of vitest, vite, and test-utils

**Closed by posva** 2024-02-15 14:53 UTC
Labels: help wanted, external
