### ISSUE TITLE
beforeUpdate and beforeLeave defined in router

### ISSUE THREAD

**Issue by 719media** [vuejs/router#1992] opened 2023-09-18 19:31 UTC
### What problem is this solving

A router can have a `beforeEnter` guard (see https://router.vuejs.org/guide/advanced/navigation-guards.html#Per-Route-Guard).

However, the router does not have a `beforeLeave` or `beforeUpdate` guard (these are defined on the component).

It would be nice if, for code organization purposes, there was the ability to define a beforeLeave or beforeUpdate at the router level.

Thanks!

### Proposed solution

`beforeUpdate` and `beforeLeave` options in a router definition

**Comment by posva** [comment] 2023-09-18 20:01
Duplicate of https://github.com/vuejs/vue-router/issues/1195

**Closed by posva** 2023-09-18 20:01 UTC
