### ISSUE TITLE
keep-alive and router-view cause subpages to render repeatedly

### ISSUE THREAD

**Issue by 13799433448** [vuejs/router#1707] opened 2023-02-20 05:59 UTC
### Version
4.1.6

### Reproduction link
[codesandbox.io](https://codesandbox.io/s/vue3-teleport-forked-61bxxv?file=/src/page1/index.vue)

### Steps to reproduce
This is my demo： https://codesandbox.io/s/vue3-teleport-forked-61bxxv?file=/src/page1/index.vue

After entering the page, click '111' to jump to another page, and you can see that the 'onMounted' method of this page is triggered twice

### What is expected?
Subpages are only rendered once

### What is actually happening?
Subpages are only rendered multiple times

**Comment by posva** [comment] 2023-02-20 08:44
Duplicate of https://github.com/vuejs/router/issues/626

**Comment by posva** [comment] 2023-02-20 08:44
Please, search existing issues and pull requests before opening issues, it saves maintainers a lot of time 🙏

**Closed by posva** 2023-02-20 08:44 UTC
