### ISSUE TITLE
Memory leak when using back button to switch between pages

### ISSUE THREAD

**Issue by nWacky** [vuejs/router#2404] opened 2024-11-15 09:42 UTC
### Reproduction

https://stackblitz.com/edit/vitejs-vite-mnz3ja?file=src%2FApp.vue

### Steps to reproduce the bug

Tested in Chrome 131 in incognito mode
Vue version: `3.5.12`
Vue router version: `4.4.5`

&ensp;

#### Build the app and start it:

1. `npm run build`
2. `npm run preview`

The issue is reproducible in dev and production mode

#### Steps to reproduce:

Open DevTools &rarr; Memory

1. go to `/`
2. click on the first link 
  `Classic Margherita Pizza (#1)`
3. click back (browser button)

You should be on the home page

Click gc, and start profiling with _Allocations on the timeline_.

Then:

1. go to a recipe that wasn't visited before
2. go back (via a browser button)
3. repeat steps 1, 2 two-three times
4. go to `/`
5. go to page 3 (link at the top of the page)

Run garbage collection again. 
Then stop memory profiling

### Expected behavior

When navigating:

- from home page (1) to recipe page (2)
- from recipe page (2) to home page (3)

Memory allocated for home page (1) should be cleared

### Actual behavior

Memory allocated for home page (1) isn't cleared

DevTools screenshot:

<img src="https://github.com/user-attachments/assets/e871cb04-dd1d-4ed4-a444-c8d4dedfe3ae" 
title="After navigating between index and recipe pages 3 times, about 4.2 MB is retained in memory.
Mostly detached DOM nodes, arrays and component objects are left" />

### Additional information

When wrapping `RouterView` in `Suspense`:

```html
<div>
  <Suspense>
    <RouterView v-slot="{ Component }">
      <component :is="Component" />
    </RouterView>
  </Suspense>
</div>
```

The memory is cleared after navigation

---

When lazy loading recipe in `/pages/recipes/[id].vue`

```ts
const recipe = ref(null);

(async () => {
  recipe.value = await apiRecipeGetById({ id, router });
})();
```

The memory is cleared after navigation

---

Originally tried reporting in https://github.com/nuxt/nuxt/issues/29854

**Comment by danielroe** [comment] 2024-11-15 12:21
i think Suspense should be within RouterView. Does it still reproduce if so?

https://vuejs.org/guide/built-ins/suspense.html#combining-with-other-components

**Comment by nWacky** [comment] 2024-11-15 13:23
When `Suspense` is inside `RouterView`:

```html
<div>
  <RouterView v-slot="{ Component }">
    <Suspense>
      <component :is="Component" />
    </Suspense>
  </RouterView>
</div>
```

The memory seems to be retained

Moving `Suspense` outside `RouterView` resolves the issue, but vue docs do say to put `Suspense` inside

**Comment by posva** [comment] 2024-11-18 22:02
Have you ensured this doesn't happen with a dynamic component within Suspense (without Vue Router)?

**Comment by adamdehaven** [comment] 2024-11-22 03:52
I played around with this a little today. I'm not sure I have a proper solution, but what I found may be interesting.

If I change the imports for the route components to be asynchronous, and change nothing else, you can see the memory for each recipe page is released when clicking the back button. 

```diff
// main.js

- import IndexView from './pages/index.vue';
- import PageThree from './pages/3.vue';
- import RecipeId from './pages/recipes/[id].vue';

const routes = [
-  { path: '/', component: IndexView },
+  { path: '/', component: async () => await import('./pages/index.vue') },
-  { path: '/3', component: PageThree },
+  { path: '/3', component: async () => await import('./pages/3.vue') },
-  { path: '/recipes/:id', component: RecipeId },
+  { path: '/recipes/:id', component: async () => await import('./pages/recipes/[id].vue') },
];
```

I _think_ this may be because your actual page components, linked to the route, are asynchronous, rather than this being handled by async components _inside_ the router view itself, and the nested Suspense is not waiting for `Component` to resolve.

You can see [in Nuxt](https://github.com/nuxt/nuxt/blob/edc299a04344897ac110aca3b3a2c2705b0cef35/packages/nuxt/src/pages/runtime/page.ts) they actually implement the internal `RouterView` a bit differently with suspense logic, etc.

I believe with the setup you have in the reproduction, you technically should have two `<Suspense>` components, with the child instance also having the `suspensible` prop set to `true` so that it will independently wait for its child nodes to resolve, rather than defering to the outermost `Suspense` parent; essentially something like this:

```vue
<template>
  <div>
    <Suspense>
      <RouterView v-slot="{ Component }">
        <Suspense suspensible>
          <component :is="Component" />
        </Suspense>
      </RouterView>
    </Suspense>
  </div>
</template>
```

With this template change in `App.vue`, and reverting the changes in `main.js` (the `await imports`) you can see that the memory is again properly released when navigating back from the recipe page.

@danielroe @posva this _feels_ like something that should be solved by documentation, but I'll defer to you all in case I missed something 🍻

**Comment by nWacky** [comment] 2024-11-22 08:54
I managed to reproduce this without vue router

<details>

<summary>Vue only reproduction</summary>

code: [vue playground](https://play.vuejs.org/#__PROD__eNrtV9ty2zYQ/ZUt0we5tkXJcTtTRta0dfOgTi8ex29hpoFISEIMAhwAlJXx6N+7AAgKuviS1jN9yYtN7C4Wiz17DsX75Oe67i8bmmTJSBeK1QY0NU09zgWraqkM3IOisxMoZFU3hpawhpmSFeQJ7sqTN7noIq/InAZnP7Urm9nFRBHD7ZBhF5OLQgptoEbrpFzBhT24NzjacV1iIVJQYTAgFNXrHcHFGO5zAaDvmCkW0GvT9JeEN/TI+wAKoikMMr8o6Yw03LQrwPNMo4SrEg/twoeHAoYuYp2LtS1wlPrmYdtwYWhVc2IorgBGJVu6h61HXEwbY6SA5SmbXeRJuPU3FzDIE/ip4Ky4jezOPL5SdMlko0ep3/2MbMPD2dA8/pOuzE6mUeprPFTwu0bXVGh/rdZmEfBoZEy3B3QI4cnpZnu6sz8ctXkapVHnkpPEaIR9xub9T1oKnFCHYZ7YMxmn6q/aMByLPMkCunlCOJd3vzmbUQ09CfZiQYvbA/ZPemVteYKd1VQtcRQ7nyFqTvES1v32nW1W5Kxk2XCMfsR5TbXkja3Rh/3SiBLLjuJctRPHDSbmN/rtymCDwqVsoW7IXLwjnG3tQ1fflPu6fx6GE7sYiLhLceBEzBEyg2n+Dd2vacFqOkFeqqZw5WyYve/bo7kiopyULcv/IGbRn3EplX+0Tlkhq7+D4eDvwWBw5GUgTWFGLb1LYkguyB1hBgS9gys8mWna6yGMki+R8KgHeM0bVlHZmFYgWieKygm87pL6elh8kcPS0gZmgJGI1/sPGPf+g8sBMJMKepyi37P1jXsYwff+6fi40yDWrxu96H389h7t6z5EbQLRVFOqILhupCE8wxxb5X20dTt87b9WlBjavkSLFsOxE+xKNgLvOUrRELH+2iHg2uD5zUqcNZwOD9t6va8UUHCirQhwps0pFiE5J1NLko0I2D2/0kqCjQEjgZQllqAoUE4rPAelLc7bZl6eYnsxM8M+wLkVyOyWfraGKDnGHpjJLO6c3REtt/JsaVXUqMdlCpfafOYUUKtqWqKlv3N9D3uNF8WZyWCoaOXgm0pVUpXBq2lZnE1ngKPJSjirV85bkdXpgrL5wiCfB4PWKpdUIU3uMiCNkRZxh7ctwEtm90r9yvYttp//32wPo3WQ9TabfXPC8JkC4LO9pAwMX0oIpgqJFP/9KhH/XSLOfvzhrCheRiIOs/W5etFo/AH5RToxwVY8phXWH+kF/ihngiLDaz1ybYnR2JDRXmzc26W0kxhXonM9wQEEvmzhnpR4zbiqCFPJISOKkVPEinJOy6kbh7CrnYHDFwvjEqazZ7edWIk4snO6PWkhOAxcib9NO1sU2p4enH4oR6nkT03eE3MQkHhiFrbfHodmwX5ZPQhiwDBGMGDov0Uu7dfKpZWj7iMwBLROtEdKvbvLf/PB8XE3/Q9OAWex1qGsRYXuaxuBBZaDnXjVfVT1a/wkQ1FCY1sC9uh3Jm5R6nCB71RMunet9RoMvqtwykgLnivkueCt/wEcHEEu)

**Reproduction steps:**

1\. click Next button (top of the page)
2\. click Previous button (top of the page)

Open DevTools &rarr; Memory.
Start _Allocation instrumentation on timeline_

1\. click next
2\. click previous

3\. click next
4\. click on any link
5\. click previous
6\. click on any link

7\. click next
8\. click previous

For navigations 3. and 5. memory is not cleared. These are the steps where the links were clicked

For other navigations (1., 2., 7., 8.) memory is cleared

&ensp;

</details>

I think the issue is due to https://issues.chromium.org/issues/376777343#comment9.

Similarly to https://github.com/vuejs/core/issues/12306#issuecomment-2458809020

**Comment by nWacky** [comment] 2024-11-22 08:55
For me changing component imports to be asynchronous and wrapping `RouterView` with `Suspense` didn't resolve the issue.

Wrapping `component :is=""` with a div in `App.vue`:

```html
<template>
  <div>
    <RouterView v-slot="{ Component }">
      <Suspense>
        <div>
          <component :is="Component" />
        </div>
      </Suspense>
    </RouterView>
  </div>
</template>
```

Seems to resolve the issue. I'm not sure why

**Comment by adamdehaven** [comment] 2024-11-22 13:49
> For me changing component imports to be asynchronous and wrapping `RouterView` with `Suspense` didn't resolve the issue.

It resolved for me 🤔 but not doing both.

> Wrapping `component :is=""` with a div in `App.vue`:
> 
> ```diff
> <template>
>   <div>
>     <RouterView v-slot="{ Component }">
>       <Suspense>
> +        <div>
>           <component :is="Component" />
> +        </div>
>       </Suspense>
>     </RouterView>
>   </div>
> </template>
> ```
> 
> Seems to resolve the issue. I'm not sure why

I did notice a warning in your original reproduction from Suspense saying it expects a single child.

**Comment by posva** [comment] 2024-11-25 08:57
Thanks for taking a deeper look. Since this can be reproduced without the router and it doesn't seem to come from it, I will close this.

FYI when I tested on Edge, I don't always see a memory leak.

**Closed by posva** 2024-11-25 08:57 UTC
