### ISSUE TITLE
replaceState fires multiple times

### ISSUE THREAD

**Issue by chf007** [vuejs/router#1526] opened 2022-08-22 03:39 UTC
### What problem does this feature solve?
`vue-router` overrides the `replaceState` method to simulate single page application routing. And when you enter the page and `push` for the first time, `replaceState` will be executed once. We have some own logic to rewrite `replaceState` to process `push` and `replace` on routes. At this time, due to the aforementioned mechanism, `replaceState` will be executed twice, and we are not good at excluding the one that is not executed by routing. 

### What does the proposed API look like?
Add a tag to distinguish the `replaceState` triggered by the route's `replace` from other `replaceStates`

current version "vue-router": "^4.0.14"

**Comment by posva** [comment] 2022-08-22 06:57
The point of replacing state is to add state to the current history entry without changing the history, it shouldn't affect your application.

> We have some own logic to rewrite replaceState to process push and replace on routes.

This worries me... Do you have side effects on those methods making them do more than they should? One of the points of using a client side router is to go through it for all the history manipulation. This is to ensure the router can function properly and is, in part, due to the shortcomings of the history api itself.

What are your rewrites doing? We can't add a such specific API to handle what already seems like a workaround of some sorts.

**Comment by posva** [comment] 2022-08-25 12:04
Duplicate of #1526

**Closed by posva** 2022-08-25 12:04 UTC
