### ISSUE TITLE
有关addRoute父子路由name、path相同时的处理结果问题

### ISSUE THREAD

**Issue by Mr-BeanSir** [vuejs/router#2391] opened 2024-10-19 05:13 UTC
### Reproduction

https://codesandbox.io/p/sandbox/vue-router-4-addroute-bug-4t7fyx

### Steps to reproduce the bug

[Vue Router warn]: Finding ancestor route "/:path(.*)*" failed for "/:path(.*)*"

### Expected behavior

在父路由被删除，`matchers.lastIndexOf(insertionAncestor, upper - 1)` 返回-1时，使用此路由的原本upper，而不是返回-1的upper

```
0 : {path: '/', redirect: undefined, name: undefined, meta: {…}, aliasOf: undefined, …}
1 : {path: '/:path(.*)*', redirect: undefined, name: 'ErrorPage', meta: {…}, aliasOf: undefined, …}
```

### Actual behavior

```
0 : {path: '/:path(.*)*', redirect: undefined, name: 'ErrorPage', meta: {…}, aliasOf: undefined, …}
1 : {path: '/', redirect: undefined, name: undefined, meta: {…}, aliasOf: undefined, …}
```

### Additional information

打开Reproduction，f12然后点击click here按钮，可以看到现在vue-router对于父子路由name，path相同时addRoute的处理结果

**Comment by posva** [comment] 2024-10-20 00:07
Duplicate of https://github.com/vuejs/router/issues/2266

**Closed by posva** 2024-10-20 00:07 UTC

**Comment by Mr-BeanSir** [comment] 2024-10-20 04:13
If the names are different, two routes will be created, as shown below
```
0: {path: '/', redirect: undefined, name: 'home', meta: {…}, aliasOf: undefined, …}
1: {path: '/:path(.*)*', redirect: undefined, name: 'ErrorPageSon', meta: {…}, aliasOf: undefined, …}
2: {path: '/:path(.*)*', redirect: undefined, name: ErrorPage, meta: {…}, aliasOf: undefined, …}
```
i hope my route list is clean,only has one ErrorPageSon route.
and i find,if have same name,but path different,it can be only created one route,maybe it's bug?

#2267 throw Error i think that reasonable for same name,This can help people know the specific cause of errors in the development environment
If it's just a warning, I think it's good to handle the routing better

The above is just my personal opinion. I just hope that my routing list can be cleaner and there will be no extra routes
