### ISSUE TITLE
Setup function called multiple times with router-view and keep-alive

### ISSUE THREAD

**Issue by mibiio** [vuejs/router#1953] opened 2023-08-07 13:47 UTC
### Reproduction

https://stackblitz.com/edit/quasarframework-2jj1tx?file=src%2Frouter%2Froutes.js

### Steps to reproduce the bug

1. Click appOne
2. Click appChildOne -> setup function called 2 times for appChildOne
3. Click appTwo
4. Click appChildOne -> setup function called 3 times for appChildOne
5. From this point on, all setup functions in all childs are called 3 times

### Expected behavior

The setup function should be called exactly one time for each component.

### Actual behavior

What happened?

When using keep-alive with router-views the setup function is called multiple times.
Following structure:

```
-MainLayout
 -AppPage
  -AppOnePage
    -ChildOne
    -ChildTwo
    -ChildThree
  -AppTwoPage
    -ChildOne
    -ChildTwo
    -ChildThree
  -AppThreePage
    -ChildOne
    -ChildTwo
    -ChildThree
```

The problem is that the setup function of all Child pages is called more often than once.

**Comment by posva** [comment] 2023-08-07 15:45
Duplicate of https://github.com/vuejs/router/issues/626

**Closed by posva** 2023-08-07 15:45 UTC
